#!/bin/bash
#
# Travis CI install script
#

# Configure git
git config --global user.email "a@a.com"
git config --global user.name "a"

echo "System stats"
echo "-----------------------------------------------------------------------"
echo "uname -a: $(uname -a)"
echo "Mercurial version: $(hg --version |
    grep -Eo "version ([0-9]+\.){2}[0-9]+" |
    awk '{print $2}')"
echo "Git version: $(git --version | awk '{print $3}')"
echo "Go version: $(go version | awk '{print $3,$4}')"
echo "-----------------------------------------------------------------------"

# Setup paths
originaldir=`echo $PWD`
gopath=`echo $GOPATH | awk '{split($0, data, ":"); print data[1]}'`
git2godir=$gopath/src/github.com/libgit2/git2go

# Download packages
go get -d -v -t ./...

# cd to git2godir
cd $git2godir

# Make sure any previous build is cleaned up
rm -rf vendor/libgit2/build vendor/libgit2/install

# Get libgit2 submodule
git submodule update --init
make install

# cd back to originaldir
cd $originaldir

# Cleanup
unset originaldir gopath git2godir
